export const PERSONNEL_TABLE_LOAD_USER_REQUEST = 'PERSONNEL_TABLE_LOAD_USER_REQUEST'
export const PERSONNEL_TABLE_LOAD_USER_SUCCESS = 'PERSONNEL_TABLE_LOAD_USER_SUCCESS'
export const PERSONNEL_TABLE_LOAD_USER_FAILED = 'PERSONNEL_TABLE_LOAD_USER_FAILED'

export const PERSONNEL_TABLE_ADD_USER_REQUEST = 'PERSONNEL_TABLE_ADD_USER_REQUEST'
export const PERSONNEL_TABLE_ADD_USER_SUCCESS = 'PERSONNEL_TABLE_ADD_USER_SUCCESS'
export const PERSONNEL_TABLE_ADD_USER_FAILED = 'PERSONNEL_TABLE_ADD_USER_FAILED'
export const PERSONNEL_TABLE_ADD_USER_RESET = 'PERSONNEL_TABLE_ADD_USER_RESET'

export const PERSONNEL_TABLE_DELETE_USER_REQUEST = 'PERSONNEL_TABLE_DELETE_USER_REQUEST'
export const PERSONNEL_TABLE_DELETE_USER_SUCCESS = 'PERSONNEL_TABLE_DELETE_USER_SUCCESS'
export const PERSONNEL_TABLE_DELETE_USER_FAILED = 'PERSONNEL_TABLE_DELETE_USER_FAILED'


export const PERSONNEL_TABLE_UPDATE_USER_REQUEST = 'PERSONNEL_TABLE_UPDATE_USER_REQUEST'
export const PERSONNEL_TABLE_UPDATE_USER_SUCCESS = 'PERSONNEL_TABLE_UPDATE_USER_SUCCESS'

export const PERSONNEL_TABLE_UPDATE_FAILED = 'PERSONNEL_TABLE_UPDATE_FAILED'

export const PERSONNEL_TABLE_UPDATE_USER_RESET = 'PERSONNEL_TABLE_UPDATE_USER_RESET'




